Science page
stjonak/nurlabs pull request #3
Opened 2021-05-05 20:33 UTC by vivianha534

**Updates to existing files**
- updated SciencePage.js to include info cards and a second header
- updated margins of the SciencePage to be smaller so that the content takes up more space
- created media query in SciencePage.css so that the vertical nav only appears on desktop and not mobile devices

**Info Card**
- InfoCard is set up assuming that the parent page has an array of objects that it will map into InfoCard. The object should have key value pairs for title, description, imgUrl, and imgAlt. (see SciencePage.js for more info)
- InfoCard currently sets the id attribute using regex to delete all spaces from the article title and lowercase the article title (ie. title: "Article 1" -> id="article1")

**Vertical Nav**
- Doesn't show up for screens smaller than 1024px (desktop)
- Hard coded anchor tag to jump to top of page so it's important that the div at the top of the page has an id="page-top"
- Takes an array of objects and uses regex to set up the anchor tags (same idea as setting up the id attribute for the InfoCard)
- Button turns blue, and text appears to the side on hover

2021-05-05 21:21 UTC, darren2hang requested changes
Nice work! I think you did a good job of separating the logic into multiple components. I left a few nits.
I think the styling of the vertical navbar can be improved a bit, like remove the border and outline and also making it more narrow, but that's just a design preference and can be addressed later.

2021-05-05 21:21 UTC, darren2hang commented on src/components/VerticalNav.js
> +          </a>
I don't think we really need a button here. Like maybe give the a tag a class and apply the nav-button properties to that class.

2021-05-05 21:21 UTC, darren2hang commented on src/styles/InfoCard.css
> +    height:50px;
```suggestion
    height: var(--navbar-height);
```

2021-05-05 21:21 UTC, darren2hang commented on src/styles/InfoCard.css
> +    height:50px;
I made a variable for the navbar height.

2021-05-09 21:23 UTC, darren2hang approved these changes

2021-05-14 02:48 UTC, vivianha534 commented
This has already been merged into setUp

2021-05-14 02:48 UTC, closed without merging