Home page
stjonak/nurlabs pull request #5
Opened 2021-05-12 16:38 UTC by vivianha534

**Created home page**
- created carousel 
- created vertical info cards
-  still need to make vertical cards mobile responsive, but will do after Joyce has finished with the graphic

2021-05-12 16:45 UTC, tr89on commented on src/components/Carousel.js
> +            <img className='banner-img' src={props.item.import ? props.item.importImg : props.item.imgSrc} />
Is there a reason to distinguish importImg and imgSrc?

2021-05-12 19:42 UTC, vivianha534 commented on src/components/Carousel.js
> +            <img className='banner-img' src={props.item.import ? props.item.importImg : props.item.imgSrc} />
importImg is if we have the img stored in our assets folder, and imgSrc is if we pull off of the internet.

2021-05-12 20:12 UTC, tr89on commented on src/components/Carousel.js
> +            <img className='banner-img' src={props.item.import ? props.item.importImg : props.item.imgSrc} />
Yeah I get that, but is there a need for the distinction between the two? Both fields essentially serve the same function

2021-05-12 20:38 UTC, vivianha534 commented on src/components/Carousel.js
> +            <img className='banner-img' src={props.item.import ? props.item.importImg : props.item.imgSrc} />
Tbh I wasn't sure, cause the hands image is stored in assets, but when I was making the component, I was pulling stock images from online, so I guess it just depends if we're gonna be using images from online when we actually deploy the site. I guess that would be something I need to ask Urna though.

2021-05-12 20:56 UTC, tr89on commented on src/components/Carousel.js
> +            <img className='banner-img' src={props.item.import ? props.item.importImg : props.item.imgSrc} />
Ok got it

2021-05-13 03:31 UTC, darren2hang requested changes
Tiny nit. I think your removal of text-align: center from the App.css might make some of the styling messed up in the other parts of the app, but it won;t be hard to fix later.
Other than my one comment, I think its good.
I recommend just merging this into setUp.

2021-05-13 03:31 UTC, darren2hang commented on src/components/VerticalCard.js
> +    marginBottom: "50px",
```suggestion
    margin: "5% 2%",
```

2021-05-14 02:58 UTC, darren2hang approved these changes
LGTM!

2021-05-14 03:30 UTC, vivianha534 commented
merged into setUp

2021-05-14 03:30 UTC, closed without merging